using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Enums
{
    [Flags]
    public enum CommandTypeEnum : short
    {
        ConnectDisconnect = 0,
        GetLoadLimit = 1,
        GRBlockLoadProfile = 2, 
        GetDailyLoadProfile = 3,
        GetInstantProfile = 4,
        GetBillingProfile = 5,
        FirmwareUpgrade = 6,
        SetRTC = 7,
        GetClockStatus = 8,
        GetRTC = 9,
        SetDemandIntegrationPeriod = 10,
        GetDemandIntegrationPeriod = 11,   
        SetProfileCapturePeriod = 12,
        GetProfileCapturePeriod = 13,
        SetSingleActionSchedule = 14,
        GetSingleActionSchedule = 15,
        SetActivityCalendarName = 16,
        GetActivityCalendarName = 17,
        SetCalendarTOD = 18,
        GetCalendarTOD = 19,
        SetCalendarActivationDate = 20,
        GetCalendarActivationDate = 21,
        ActivateCalendar = 22,
        SetLLSSecretMRChange = 23,
        SetHLSKeyUSChange = 24,
        SetHLSKeyFWChange = 25,
        SetGlobalKeyChange = 26,
        SetESWFChange = 27,
        GetESWF = 28,
        SetMDReset = 29,
        SetInstantCapturePeriod = 30,
        GetInstantCapturePeriod = 31,
        GetNamePlate = 32,
        GetControlEvent = 33,
        GetCurrentEvent = 34,
        GetNonRolloverEvent = 35,
        GetPowerEvent = 36,
        GetTransactionEvent = 37,
        GetVoltageEvent = 38,
        GetRelayStatus = 39,
        GetCurrentLimit = 40,
        SetCurrentLimit = 41,
        GetVoltageEventProfile = 42,
        GetCurrentEventProfile = 43,
        GetPowerEventProfile = 44,
        GetTransactionEventProfile = 45,
        GetOtherEventProfile = 46,
        GetNonRollOverEventProfile = 47,
        GetControlEventProfile = 48,
        GetNetMeteringMode = 49,
        SetNetMeteringMode = 50,
        GetPaymentMode = 51,
        SetPaymentMode = 52,
        GetPrepaidBalance = 53,
        SetPrepaidBalance = 54,
        GetLastRechargeAmount = 55,
        SetLastRechargeAmount = 56,
        GetTotalAmountAtLastRecharge = 57,
        SetTotalAmountAtLastRecharge = 58,
        GetCurrentBalanceTime = 59,
        SetCurrentBalanceTime = 60,
        GetLastRechargeTime = 61,
        SetLastRechargeTime = 62,
        SetLoadLimit = 63,
        GetBlockLoadProfile = 64,
        MeterType = 65,
        ESW = 66,
        DI = 67
    }
}
